name: CI/CD Pipeline to ECR

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: dreamcometrue-repo
  DEPLOYMENT_REPO: IbrahimmAdel/dreamcometrue-yaml

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

  build-scan-push:
    name: Build, Scan and Push to ECR
    runs-on: ubuntu-latest
    needs: test
    
    permissions:
      id-token: write   
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  update-deployment:
    name: Update Deployment Repo
    runs-on: ubuntu-latest
    needs: build-scan-push
    
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Checkout deployment repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.DEPLOYMENT_REPO }}
        token: ${{ secrets.PAT }}
        path: deployment-repo
        ref: master
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Get ECR registry URL
      id: ecr-url
      run: |
        ECR_REGISTRY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
        echo "registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT
        
    - name: Update deployment.yaml
      run: |
        cd deployment-repo
        
        IMAGE_URI="${{ steps.ecr-url.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
                
        sed -i "s|image:.*|image: $IMAGE_URI|" deployment.yaml
        
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add deployment.yaml
        git commit -m "CI: Update image to ${{ github.sha }}"
        git push
